Citizen.CreateThread(function()
	AddTextEntry("MRSA", "MRSA")
    AddTextEntry("EMSAMB", "Ambulance")
	AddTextEntry("EMSSUV", "Supervisor")
	AddTextEntry("EMSORT", "Organ Transport")
    AddTextEntry("EMSHELI", "Air Ambulance")
	AddTextEntry("WT_V_SLTFLIR", "Searchlight & FLIR")
	AddTextEntry("WT_MEDBAG", "Medical Bag")
	AddTextEntry("WT_DONATION", "Nacho's Generous Donation")
	AddTextEntry("AM_H_CNVRT", "Hold ~INPUT_VEH_ROOF~ when stationary to use special vehicle features.")
end)